export const dutyOption = [
  { value: '서버/백엔드', label: '서버/백엔드' },
  { value: '프론트엔드', label: '프론트엔드' },
  { value: '웹 풀스택', label: '웹 풀스택' },
  { value: '안드로이드 앱', label: '안드로이드 앱' },
  { value: 'ios 앱', label: 'ios 앱' },
  { value: 'PHP 개발자', label: 'PHP 개발자' },
  { value: 'DevOps/시스템 관리자', label: 'DevOps/시스템 관리자' },
  { value: '머신러닝', label: '머신러닝' },
  { value: '인공지능(AI)', label: '인공지능(AI)' },
  { value: '데이터 엔지니어', label: '데이터 엔지니어' },
  { value: '소프트웨어 엔지니어', label: '소프트웨어 엔지니어' },
  { value: '빅데이터 엔지니어', label: '빅데이터 엔지니어' },
  { value: 'QA, 테스트 엔지니어', label: 'QA, 테스트 엔지니어' },
  { value: '모바일 게임', label: '모바일 게임' },
  { value: '게임 클라이언트', label: '게임 클라이언트' },
  { value: '게임 서버', label: '게임 서버' },
  { value: '개발 매니저', label: '개발 매니저' },
  { value: '시스템/네트워크', label: '시스템/네트워크' },
  { value: '시스템 소프트웨어', label: '시스템 소프트웨어' },
  { value: '데이터 사이언티스트', label: '데이터 사이언티스트' },
  { value: '인터넷 보안', label: '인터넷 보안' },
  { value: 'PM, 프로덕트 메니저', label: 'PM, 프로덕트 메니저' },
  { value: '사물인터넷(IoT)', label: '사물인터넷(IoT)' },
  { value: '응용프로그램', label: '응용프로그램' },
  { value: '블록체인', label: '블록체인' },
  { value: '선택안함', label: '선택안함' },
];

export default dutyOption;
